modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/0x00002a/Soul-Shards-Despawn/"
license = "MIT"

[[mods]]
modId = "soulshards"
version = "${version}"
displayName = "Soul Shards Despawn"
authors = "0x00002a"
description = '''
Custom spawners for any and all mobs!
'''
logoFile = "icon.png"

[[dependencies.soulshards]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.soulshards]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.soulshards]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.soulshards]]
modId = "jei"
mandatory = false
versionRange = "[${jei_version},)"

[[dependencies.soulshards]]
modId = "cloth-config"
mandatory = false
versionRange = "[${cloth_config_version},)"