[versions]
# The latest versions are available at https://lambdaurora.dev/tools/import_quilt.html
minecraft = "1.21.1"

fabric_loader = "0.16.5"
fabric_api = "0.92.0+1.20.1"

wthit = "8.15.2"
clothconfig = "11.1.136"
modmenu = "7.2.2"
jei = "15.19.5.99"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }

# If you have multiple similar dependencies, you can declare a dependency bundle and reference it on the build script with "libs.bundles.example".
[bundles]

[plugins]