[versions]
# The latest versions are available at https://lambdaurora.dev/tools/import_quilt.html
minecraft = "1.21.1"

fabric_loader = "0.19.2"
fabric_api = "0.116.11+1.21.1"

wthit = "12.10.2"
clothconfig = "15.0.140"
modmenu = "11.0.4"
jei = "19.27.0.340"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }

# If you have multiple similar dependencies, you can declare a dependency bundle and reference it on the build script with "libs.bundles.example".
[bundles]

[plugins]