dependencies {
    // We depend on fabric loader here to use the fabric @Environment annotations and get the mixin dependencies
    // Do NOT use other classes from fabric loader
    /*modImplementation "net.fabricmc:fabric-loader:${libs.versions.fabric.loader.get()}"
    modCompileOnly "mcp.mobius.waila:wthit-api:fabric-${libs.versions.wthit.get()}"
    modApi("me.shedaniel.cloth:cloth-config:${libs.versions.clothconfig.get()}")
    modApi "com.terraformersmc:modmenu:${libs.versions.modmenu.get()}"
    modCompileOnlyApi "mezz.jei:jei-${libs.versions.minecraft.get()}-common-api:${libs.versions.jei.get()}"
    modRuntimeOnly "mezz.jei:jei-${libs.versions.minecraft.get()}-common:${libs.versions.jei.get()}"*/
}

